class ApplicationViewComponent < ViewComponentContrib::Base
  extend Dry::Initializer

  # https://github.com/ViewComponent/view_component/issues/639#issuecomment-816969723
  def self.initialize_parameters: () -> untyped

  private

  def identifier: () -> untyped
end
