require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/text_inputs", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # TextInput. As you add validations to TextInput, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TextInput.create! valid_attributes
      get text_inputs_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TextInput" do
        expect {
          post text_inputs_url, params: {text_input: valid_attributes}
        }.to change(TextInput, :count).by(1)
      end

      it "redirects to the created text_input" do
        post text_inputs_url, params: {text_input: valid_attributes}
        expect(response).to redirect_to(text_input_url(TextInput.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TextInput" do
        expect {
          post text_inputs_url, params: {text_input: invalid_attributes}
        }.not_to change(TextInput, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post text_inputs_url, params: {text_input: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested text_input" do
      text_input = TextInput.create! valid_attributes
      expect {
        delete text_input_url(text_input)
      }.to change(TextInput, :count).by(-1)
    end

    it "redirects to the text_inputs list" do
      text_input = TextInput.create! valid_attributes
      delete text_input_url(text_input)
      expect(response).to redirect_to(text_inputs_url)
    end
  end
end
