development:
  adapter: async

test:
  adapter: test

production:
  # async adapter is not proper for production, redis is recommended
  adapter: async
  #  adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: sample_hotwire_production
